-- This tool's database schema is now part of the canonical DOME governance schema.
-- See: dome-docs/templates/governance_schema.sql
--
-- For in-place upgrades to existing deployments, see:
-- dome-docs/migrations/
--
-- This file is retained as a stub so existing README links don't 404.
